### ISSUE TITLE
Eyes.Open always gives error StartSession failed: response is null

### ISSUE THREAD

**Issue by LawrenceAntony** [applitools/WinAppDriver-Examples#1]
I was trying to use the sample c# code provided in this repository but it throws error "StartSession failed: response is null "

Stack Trace :

   at Applitools.ServerConnector.StartSessionInternal(SessionStartInfo startInfo)
   at Applitools.ServerConnector.StartSession(SessionStartInfo startInfo)
   at Applitools.EyesBase.StartSession_()
   at Applitools.EyesBase.EnsureRunningSession()
   at Applitools.EyesBase.OpenBase()
   at Applitools.EyesBase.OpenBase(String appName, String testName, RectangleSize viewportSize)
   at Applitools.EyesBase.OpenBase(String appName, String testName, Size viewportSize)
   at Applitools.Appium.Eyes.Open(RemoteWebDriver driver, String appName, String testName)
   at CalculatorTest.ScenarioStandard.Addition() in C:\Users\Maria Lawrence Anton\Downloads\C#\ScenarioStandard.cs:line 45

Can someone help me on this

**Comment by itaibh** [comment]
Hello Lawrence,
I can check it on my spare time, but if you want to file an official issue you should contact our technical support team at https://help.applitools.com/hc/en-us/requests/new

Itai Bar-Haim,
DevPlatforms developer at Applitools.
